using Serenity.Navigation;
using MyPages = SerExtraCore.Transactions.Pages;

[assembly: NavigationMenu(20000, "Transactions",  icon: "fa fa-sitemap")]
[assembly: NavigationLink(int.MaxValue, "Transactions/Clearance", typeof(MyPages.ClearanceController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Consignment", typeof(MyPages.ConsignmentController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Consignment Charges", typeof(MyPages.ConsignmentChargesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice", typeof(MyPages.InvoiceController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Charges", typeof(MyPages.InvoiceChargesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Collection", typeof(MyPages.InvoiceCollectionController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Collection Details", typeof(MyPages.InvoiceCollectionDetailsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Consignment Vehicle Details", typeof(MyPages.ConsignmentVehicleDetailsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Vehicle Details", typeof(MyPages.InvoiceVehicleDetailsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Consignment Trip Dates", typeof(MyPages.ConsignmentTripDatesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Trip Dates", typeof(MyPages.InvoiceTripDatesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Suppliers Payment", typeof(MyPages.SuppliersPaymentController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Suppliers Payment Invoices", typeof(MyPages.SuppliersPaymentInvoicesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Suppliers Payment Invoice Vehicle Details", typeof(MyPages.SuppliersPaymentInvoiceVehicleDetailsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Consignment Vehicle Specifications", typeof(MyPages.ConsignmentVehicleSpecificationsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Vehicle Specifications", typeof(MyPages.InvoiceVehicleSpecificationsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Invoice Due Details", typeof(MyPages.InvoiceDueDetailsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Suppliers Payment Invoice Charges", typeof(MyPages.SuppliersPaymentInvoiceChargesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Quotations", typeof(MyPages.QuotationsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Quotation Details", typeof(MyPages.QuotationDetailsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Purchase", typeof(MyPages.PurchaseController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Purchase Details", typeof(MyPages.PurchaseDetailsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Transactions/Delivery Services", typeof(MyPages.DeliveryServicesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Transactions/Delivery Service Details", typeof(MyPages.DeliveryServiceDetailsController), icon: null)]
